services:
  postgres:
    image: postgres:18
    container_name: ci-cd-postgres
    environment:
      POSTGRES_DB: cicdservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cicdservice"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ci-cd-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ci-cd-postgres:5432/cicdservice
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_healthy