spring.application.name=ci-cd-service

#TODO: Change later
spring.jpa.hibernate.ddl-auto=update

#TODO: Move to a secrets vault later and use stronger encryption algorithm
jasypt.encryptor.password=MySecretKey12345MySecretKey12345